{% set build = 1 %}
{% set version = "0.0.1.dev0" %}
{% set commit = "073de0045c4a1b986081fc4164c290d7de510c85" %}
{% set sha = "594241ecd8e48f8d52f96875fd2c5a80dca7899148f4e772fd45b6ab99d6056e" %}

package:
  name: dynare-preprocessor
  version: {{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/{{ commit }}.tar.gz
  sha256: {{ sha }}

build:
  number: {{ build }}

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - {{ stdlib("c") }}
    - meson
    - ninja
    - bison         # [unix]
    - flex          # [unix]
    - winflexbison  # [win]
    - pkg-config
  host:
    - libboost-headers
    - pthread-stubs  # [linux]

test:
  files:
    - example1.mod

about:
  home: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  doc_url: https://www.dynare.org/manual/
  dev_url: https://git.dynare.org/Dynare/preprocessor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
