{% set build = 0 %}
{% set version = "0.0.1" %}

package:
  name: dynare-preprocessor
  version: {{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a3b0e13ae1917607427c0fd47f4e45e992a4715000df0fc2a02b8d8fb30851d1

build:
  number: {{ build }}

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - {{ stdlib("c") }}
    - meson
    - ninja
    - bison         # [unix]
    - flex          # [unix]
    - winflexbison  # [win]
    - pkg-config
  host:
    - libboost-headers
    - pthread-stubs  # [linux]

test:
  files:
    - example1.mod

about:
  home: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  doc_url: https://www.dynare.org/manual/
  dev_url: https://git.dynare.org/Dynare/preprocessor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
